name: Collect Hydra Results

on:
  workflow_dispatch:
  schedule:
    - cron: "3 14 * * *"

env:
  GH_PUB_KEY: github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
  GH_BOT_ACC_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
  GH_BOT_ACC_NAME: github-actions[bot]

jobs:
  collect:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.GH_SSH_PRIVATE_KEY }}
          known_hosts: $GH_PUB_KEY
          name: id_ed25519

      - name: setup git
        run: |
          git config --local user.email $GH_BOT_ACC_EMAIL
          git config --local user.name $GH_BOT_ACC_NAME
          git remote add ssh "git@github.com:${{ github.repository }}"

          git fetch origin
          git checkout results

      - name: Back prev results
        run: |
          mv results/concerned-failures.json previous.json

      - name: Run collect script
        run: |
          nix run github:${{ github.repository }}

      - name: Open issue for new build failures
        run: |
          GH_REPOSITORY=${{ github.repository }} \
            GH_TOKEN=${{ secrets.GITHUB_TOKEN }} python create-issues.py

      - name: Cleanup
        run: |
          rm ./previous.json

      - name: Commit results
        run: |
          git add results/
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update Hydra results"
            git push ssh results --force
          fi
